const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/index'))
  .get('/enamel-pins', (req, res) => res.render('pages/enamel-pins'))
  .get('/apparel', (req, res) => res.render('pages/apparel'))
  .get('/misc', (req, res) => res.render('pages/misc'))
  .get('/about-us', (req, res) => res.render('pages/about-us'))
  .get('/contact', (req, res) => res.render('pages/contact'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
